version: 2
jobs:
  build:
    environment:
      - MALLOC_CHECK_: 7
      - MALLOC_PERTURB_: 42
      - GTEST_SHUFFLE: 1
      - GTEST_RUNTIME_LIMIT: 199
    docker:
      - image: circleci/buildpack-deps:18.04-browsers
    steps:
      - run: sudo apt update -q && sudo apt install cmake libgtest-dev clang-format
      - checkout
      - run:
          command: |
            git fetch--unshallow || true
            git fetch --tags --prune
#      - run:
#          command: |
#            git submodule sync
#            git submodule update --init --recursive
#            git submodule foreach --recursive git fetch --tags --prune
      - run:
          command: |
            c++ --version
            cmake --version
      - run: cmake .
      - run: make --keep-going all
      - run: |
          ulimit -c unlimited
          make --keep-going test
      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv -t /tmp/artifacts core.* ./Testing/Temporary/*.log
          when: on_fail
      - run:
          command: |
            if make reformat && [[ -n $(git diff) ]]; then
              echo "You must run 'make reformat' before submitting a pull request"
              echo ""
              git --no-pager diff
              exit -1
            fi
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
